tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 1241571c-e310-4e3d-8f26-a846dc33b1c7 # social image
        instructions: null
        label: null
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 70dbe9f0-38b1-4e95-b403-bb4291e4df26
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 651ff65c-6bf7-4eb4-a020-92dc10bb004f # social name
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 7c4a802d-4cf6-465b-b046-f914878e0bdd
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: 2ff62a3a-7474-4bbc-8ddb-7fd6a35d7462
    userCondition: null
