fieldLayouts:
  34e13e0b-0ce0-4a84-afc9-555ecb44afe1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4e3161c-9a0b-4989-ae2c-a7408e877c9b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26ae5ff0-1c20-4996-8ca3-d39e352f5f51
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
section: 721ca285-b527-4f49-a8a3-fe39d7bf6625 # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
