fieldLayouts:
  34e13e0b-0ce0-4a84-afc9-555ecb44afe1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4e3161c-9a0b-4989-ae2c-a7408e877c9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 71be2c8f-d8f8-48a6-80a5-69d9405a4c6e # Contact Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c334d70b-77d3-4609-bd8e-a593aa28c62c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f27f95b7-d0f8-4d42-889d-9c5fac6801e9 # Social Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99fc79a3-a033-46e0-ac32-48697b3b3bbe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26ae5ff0-1c20-4996-8ca3-d39e352f5f51
        userCondition: null
handle: contact
hasTitleField: true
name: Contact
section: 721ca285-b527-4f49-a8a3-fe39d7bf6625 # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
