fieldLayouts:
  58d34772-778f-4577-b637-509a78dac462:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 26b9f32d-55f0-470c-b16c-8bfba250a0a7 # Fold title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c253925-5b1b-431b-bd99-c6dcf72b9e81
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 256ab9c7-b4f0-4823-b55e-264c6514035e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4f68ba6-b1ad-40d9-8e66-25f943be90a9 # Fold image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eee12da7-9509-4fbd-83a3-6923c3cacfd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f33f3627-6b49-4717-b33f-a74aa57fc237 # Fold text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 520da91a-556a-44df-8a04-ebe2b14d34f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87a8749e-4eb9-4aa2-858e-95b85b344bd0
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 21038002-abbe-49d2-8d3e-1253f7f381e5 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
