fieldLayouts:
  915da9d5-3184-465d-b6b0-319ec16f744f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9196cb53-4093-4fde-afd6-056f4d0495c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cdda45a-f36b-4596-881d-1d591c64419b # work type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7902f486-c87e-4e82-bf38-5d97258f9456
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b625fb03-11a3-4712-a711-a4c007b7e680 # Project Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6cca1b7-ef4f-424b-b60c-fa6d97600e81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdce4c0f-87d5-4cbe-9ef1-6dc9f3ad5790 # Project Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 591132af-598e-4fef-be96-8a949ac28453
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3f755a7-f851-4ec8-99a3-bc56a6ff887c # global Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5903d254-903b-4cd8-b578-dbe2c009bf09
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e0578ec-49a0-4f17-a6e1-f003bb66fd53
        userCondition: null
handle: projects
hasTitleField: true
name: Projects
section: 43152f16-1cbd-44a8-bf66-aa0c38d63287 # Projects
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
