defaultPlacement: end
fieldLayouts:
  d816d475-8ef6-43f9-8def-688d9a945b6f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 0bfc4789-e2c0-4bf2-9cc9-99f1b75b7d42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ae2c871-d1e4-4e51-9748-3a3bc73b6159
        userCondition: null
handle: function
name: 'job function'
siteSettings:
  7d27545e-9618-4303-8c44-281674ee08a8: # agency
    hasUrls: true
    template: null
    uriFormat: 'function/{slug}'
structure:
  maxLevels: null
  uid: fa95deb2-2425-4110-8e78-1adf2ec7d4e5
