fieldLayouts:
  ed1bffe1-f9ec-4e45-948a-4353c2319f80:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1a20a744-8390-4df1-9312-760e7bcf5d72
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d375ab6-b3b4-4534-97e1-daeae472b9a9
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
