columnSuffix: lyivivbj
contentColumnType: text
fieldGroup: 96c0e878-1561-454d-9934-ce4afcd4834c # Home
handle: foldTitle
instructions: null
name: 'Fold title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
