columnSuffix: null
contentColumnType: string
fieldGroup: 37d48be1-0a84-4ec8-adb6-fa4f840845f2 # Team
handle: members
instructions: null
name: Members
searchable: false
settings:
  contentTable: '{{%matrixcontent_members}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
