columnSuffix: null
contentColumnType: string
fieldGroup: 568b898b-0700-4453-9720-6f82facd7a69 # Common
handle: socialMedia
instructions: null
name: 'Social Media'
searchable: false
settings:
  contentTable: '{{%matrixcontent_socialmedia}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
