defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  7d27545e-9618-4303-8c44-281674ee08a8: # agency
    enabledByDefault: true
    hasUrls: true
    template: _/pages/contact.twig
    uriFormat: contact
type: single
