defaultPlacement: end
enableVersioning: true
handle: projectsList
name: 'Projects list'
propagationMethod: all
siteSettings:
  7d27545e-9618-4303-8c44-281674ee08a8: # agency
    enabledByDefault: true
    hasUrls: true
    template: _/pages/projects/projects.twig
    uriFormat: projects
type: single
