tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: a04a968f-65f3-44fb-847c-3a3e1d0a5cfb # Link Text
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0dbeec62-b501-45bc-8cb9-b15a4fcd293c
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 279a85b7-7d64-48cb-ab59-300389993774 # Link Destination
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 855d59d1-7911-4682-a31f-d00d44ed19b8
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: 739fde37-f67c-4413-9d7b-f291d2a35889
    userCondition: null
